<a href="https://colab.research.google.com/github/vinay-blip/ml_model_code/blob/main/model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd
import numpy as np
import glob
glass = glob.glob('dataset/glass/*.*')
metal = glob.glob('dataset/metal/*.*')
paper = glob.glob('dataset/paper/*.*')
plastic = glob.glob('dataset/plastic/*.*')
data = []
labels = []
for i in glass:   
    image=tf.keras.preprocessing.image.load_img(i, color_mode='rgb', 
    target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(0)
for i in metal:   
    image=tf.keras.preprocessing.image.load_img(i, color_mode='rgb', 
    target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(1)  
for i in paper:   
    image=tf.keras.preprocessing.image.load_img(i, color_mode='rgb', 
    target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(2)
for i in plastic:   
    image=tf.keras.preprocessing.image.load_img(i, color_mode='rgb', 
    target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(3)

data = np.array(data)
labels = np.array(labels)

X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2,
                                                random_state=42)

In [2]:
classes = ['glass','metal','paper','plastic']
X_train = X_train / 255
X_test = X_test / 255

In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16,(3,3),activation='relu',input_shape=(200,200,3)),
    tf.keras.layers.MaxPool2D(2,2),
    #
    tf.keras.layers.Conv2D(32,(3,3),activation='relu'),
    tf.keras.layers.MaxPool2D(2,2),
    #
    tf.keras.layers.Conv2D(64,(3,3),activation='relu'),
    tf.keras.layers.MaxPool2D(2,2),
    #
    tf.keras.layers.Flatten(),
    #
    tf.keras.layers.Dense(512,activation='relu'),
    #
    tf.keras.layers.Dense(4,activation='sigmoid')
])


In [7]:
model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy']
             )
model_fit = model.fit(X_train, y_train, steps_per_epoch=50, epochs = 5)

Epoch 1/5
50/50 [==============================] - 186s 2s/step - loss: 1.1166 - accuracy: 0.5066
Epoch 2/5
50/50 [==============================] - 79s 2s/step - loss: 0.8682 - accuracy: 0.6344
Epoch 3/5
50/50 [==============================] - 80s 2s/step - loss: 0.6639 - accuracy: 0.7432
Epoch 4/5
50/50 [==============================] - 79s 2s/step - loss: 0.4836 - accuracy: 0.8156
Epoch 5/5
50/50 [==============================] - 80s 2s/step - loss: 0.3211 - accuracy: 0.8823


In [8]:
model.evaluate(X_test,y_test)

13/13 [==============================] - 6s 457ms/step - loss: 1.1969 - accuracy: 0.6432


[1.1968663930892944, 0.643216073513031]

In [14]:
y_pred = model.predict(X_test)
y_pred[:5]

13/13 [==============================] - 5s 367ms/step


array([[0.73839676, 0.39740288, 0.58348113, 0.36516064],
       [0.28072345, 0.3232503 , 0.5137668 , 0.79007345],
       [0.6841931 , 0.15770185, 0.11888638, 0.9226688 ],
       [0.00194221, 0.3916418 , 0.99928164, 0.9021803 ],
       [0.10878314, 0.02427763, 0.11175458, 0.99215305]], dtype=float32)

In [16]:
y_classes = [np.argmax(element) for element in y_pred]
y_classes[:10]

array([0, 3, 1, 2, 3, 0, 2, 3, 2, 2])

In [17]:
y_test[:10]

array([0, 3, 1, 2, 3, 0, 2, 3, 2, 2])